#!/usr/bin/env groovy
properties([
        parameters([
                [$class: 'BuildSelectorParameter',
                 defaultSelector: upstream(),
                 description: '',
                 name: 'copyArtifactSelector']]),
        buildDiscarder(
                logRotator(
                        artifactDaysToKeepStr: '',
                        artifactNumToKeepStr: '10',
                        daysToKeepStr: '',
                        numToKeepStr: '15')),
        disableConcurrentBuilds(),
        pipelineTriggers([
                pollSCM('H/5 * * * *')
        ])
])

node {
    checkout scm
    stage ('Print envs') {
        sh 'printenv'
    }
}