#!/usr/bin/env groovy
properties([
        parameters([
//                [$class: 'BuildSelectorParameter',
//                 defaultSelector: upstream(),
//                 description: '',
//                 name: 'copyArtifactSelector'],
                string(name: 'UpstreamJobName'),
                string(name: 'UpstreamBuildNumber')
        ]),
        buildDiscarder(
                logRotator(
                        artifactDaysToKeepStr: '',
                        artifactNumToKeepStr: '10',
                        daysToKeepStr: '',
                        numToKeepStr: '15')),
        disableConcurrentBuilds(),
        pipelineTriggers([
                pollSCM('H/5 * * * *')
        ])
])

node {
    checkout scm
    stage ('Print envs') {
        sh 'env'
    }
//    copyArtifacts(projectName: "MB1/${env.BRANCH_NAME}",
//            selector: [$class: 'ParameterizedBuildSelector',
//                       parameterName: 'copyArtifactSelector'] )
    copyArtifacts(
            projectName: UpstreamJobName,
            selector: specific(UpstreamBuildNumber),
            flatten: true,
            target: 'upstreamArtifact',
            filter: '*.txt',
            fingerprintArtifacts: true
    )
    sh 'ls -a'
    sh 'ls -a upstreamArtifact'

    dir('upstreamArtifact') {
        files = findFiles(glob: '*.txt') //Pipeline Utility Steps
        files.each { file ->
            println "Path ${file.path}"
        }
        deleteDir()
    }
}
